name: Deploy prerequisites

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: write
    
jobs:
  deploy-prerequisites:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Bicep deploy
        id: bicep-deploy
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          template: infra/01-prerequisites/main.bicep
          region: ${{ vars.AZURE_LOCATION }}
          parameters: >
            location=${{ vars.AZURE_LOCATION }}
          deploymentName: deploy-aca-gh-runners-dev-prerequisites
  
      - name: Update GitHub variables
        run: |
          gh variable set PROJECT --body ${{ steps.bicep-deploy.outputs.project }}
          gh variable set RG_NAME --body ${{ steps.bicep-deploy.outputs.rgName }}
          gh variable set ACR_NAME --body ${{ steps.bicep-deploy.outputs.acrName }}
          gh variable set ACA_ENV_NAME --body ${{ steps.bicep-deploy.outputs.acaEnvName }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          az acr build -r ${{ steps.bicep-deploy.outputs.acrName }} -g ${{ steps.bicep-deploy.outputs.rgName }} -f src/Dockerfile.from-base -t runners/github/linux:from-base src
        name: Build and push runner image to the registry
