name: Create and register self-hosted runners

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: infra
    
jobs:
  provision-runners:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true

    steps:
      - uses: actions/checkout@v3

      - name: Generate access token
        id: generate-access-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          skip-token-revoke: true

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      
      - name: Get prerequisites outputs
        id: get-prerequisites-outputs
        uses: azure/CLI@v1
        with:
          inlineScript: |
            suffix=$(az deployment sub show -n deploy-aca-gh-runners-dev-prerequisites --query properties.outputs.suffix.value -o tsv)
            rgName=$(az deployment sub show -n deploy-aca-gh-runners-dev-prerequisites --query properties.outputs.rgName.value -o tsv)
            acrName=$(az deployment sub show -n deploy-aca-gh-runners-dev-prerequisites --query properties.outputs.acrName.value -o tsv)
            acaEnvName=$(az deployment sub show -n deploy-aca-gh-runners-dev-prerequisites --query properties.outputs.acaEnvName.value -o tsv)
            echo "suffix=$suffix" >> $GITHUB_OUTPUT
            echo "rgName=$rgName" >> $GITHUB_OUTPUT
            echo "acrName=$acrName" >> $GITHUB_OUTPUT
            echo "acaEnvName=$acaEnvName" >> $GITHUB_OUTPUT
      
      - name: Bicep deploy
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ steps.get-prerequisites-outputs.outputs.rgName }}
          template: ./infra/02-app/main.bicep
          parameters: >
            suffix=${{ steps.get-prerequisites-outputs.outputs.suffix }} 
            acrName=${{ steps.get-prerequisites-outputs.outputs.acrName }} 
            acaEnvName=${{ steps.get-prerequisites-outputs.outputs.acaEnvName }} 
            imageTag=other.1111.01 
            gitHubAccessToken=${{ steps.generate-access-token.outputs.token }} 
            gitHubOrganization=${{ github.repository_owner }} 
            # gitHubAppPrivateKey=<<EOL
            # ${{ secrets.GH_APP_PRIVATE_KEY }}
            # EOL
          deploymentName: deploy-aca-gh-runners-dev-app
